services:
  - type: web
    name: uso-api
    env: go
    buildCommand: go build -o app cmd/server/main.go
    startCommand: ./app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: uso-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 8080

databases:
  - name: uso-db
    databaseName: uso_db
    user: uso